services:
  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # 挂载开发环境配置
      - ./nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - my-server

  app:
    container_name: claw_step_serve
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    # expose:
    #   - "3000"
    ports:
      - "${APP_PORT:-3000}:3000"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - my-server
    volumes:
      - .:/app                    # 挂载源代码目录
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    expose:
      - "6379"
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - my-server
    command: redis-server --requirepass ${REDIS_PASSWORD:-bipwqhso2aH} --appendonly yes

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bipwqhso2aH}
      POSTGRES_DB: ${POSTGRES_DB:-clawstep}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - my-server

networks:
  my-server:
    driver: bridge